### ISSUE TITLE
500 error with InvalidAuthenticityToken execption

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#103]
A bunch of 500 errors in the LR logs triggered an investigation into the cause.

They are associated with the following entriyfrom the PPD app rails production.log:

```
INFO 2020-02-21T06:21:09.128+00:00 [landregistry.data] [099cd004-28a7-4601-811b-5399b58aa68c] Started POST "/app/ppd/search" for 103.69.146.171
WARN 2020-02-21T06:21:09.129+00:00 [landregistry.data] [099cd004-28a7-4601-811b-5399b58aa68c] No explicit error page for exception ActionController::InvalidAuthenticityToken - ActionController::InvalidAuthenticityToken

```

If this is a bad requeset, it should return a 400 error, not a 500.

**Comment by ijdickinson** [comment]
Migrated to https://github.com/epimorphics/hmlr-linked-data/issues/37
