### ISSUE TITLE
UI change: Date selector overflowing container

### ISSUE THREAD

**Issue by lizscuffell** [epimorphics/ppd-explorer#121]
When selecting the date range, the calendar feature overflows its container
![image](https://user-images.githubusercontent.com/37189169/93852692-65284800-fcaa-11ea-82d8-18ff76b69eeb.png)

**Comment by ijdickinson** [comment]
@lizscuffell Fixed by replacing with native control

**Comment by lizscuffell** [comment]
Issue fixed. Closing ticket
