### ISSUE TITLE
Add locality to search

### ISSUE THREAD

**Issue by mairead** [epimorphics/ppd-explorer#140]
**As a user I** would like to search by locality field

**Business requirements:**
While searching for price paid data, it's possible to click on the icon to add the "Locality" to the filter on each entry. This field isn't on the search settings form itself, so it's not possible to change the locality without first finding a property that's in the locality of interest. And returning to change search settings removes any locality filter.

**Tasks**
- Add locality to search form

**Acceptance criteria**
- You can search results by locality only
- You can see locality populated if you return to the search form after selecting it

**Comment by ijdickinson** [comment]
@mairead Apologies, I should have briefed you that we've been gradually moving to a [shared issues list for the HMLR apps](https://github.com/epimorphics/hmlr-linked-data/issues).

I'll close this issue here, and migrate the ticket to the shared list.

**Comment by ijdickinson** [comment]
Migrated to https://github.com/epimorphics/hmlr-linked-data/issues/39
