### ISSUE TITLE
Startup and shutdown logs not json

### ISSUE THREAD

**Issue by mika018** [epimorphics/ppd-explorer#148]
At the moment startup and shutdown logs are not in json format:
```
=> Booting Puma
=> Rails 5.2.6 application starting in production 
=> Run `rails server -h` for more startup options
{"level":"INFO","ts":"2021-11-23T10:04:36.947Z","message":"Raven 3.1.2 ready to catch errors","rails":{"environment":"production"}}
Puma starting in single mode...
* Puma version: 5.5.1 (ruby 2.6.6-p146) ("Zawgyi")
*  Min threads: 0
*  Max threads: 5
*  Environment: production
*          PID: 1
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
```
and
```
- Gracefully stopping, waiting for requests to finish
Exiting
``

We would like them as json so that they get through to kibana and we know whether the application shut down gracefully.

**Comment by ijdickinson** [comment]
This is unlikely to be possible. A more achievable goal would be to suppress these startup and shutdown message from Puma altogether.

**Comment by mika018** [comment]
It would be beneficial for us to know whether he app shut down gracefully or it crashed. This can also be achieved with an error counter metric, but preferably we would have both.

**Comment by ijdickinson** [comment]
After a bit of experimentation, I found I can achieve this:

```text
ian@alder $ rails server -e production
{ message: 'Starting Puma' }
{ message: 'Puma starting in single mode...' }
{ message: '* Puma version: 5.3.2 (ruby 2.6.6-p146) ("Sweetnighter")' }
{ message: '*  Min threads: 5' }
{ message: '*  Max threads: 5' }
{ message: '*  Environment: production' }
{ message: '*          PID: 29978' }
{ message: '* Listening on http://0.0.0.0:3000' }
{ message: 'Use Ctrl-C to stop' }
^C{ message: '- Gracefully stopping, waiting for requests to finish' }
{ message: '=== puma shutdown: 2021-11-25 10:19:40 +0000 ===' }
{ message: '- Goodbye!' }
Exiting
```

Note that it's **nearly** all JSON, except for `Exiting`. That's in principle fixable, but only by a level of monkey-patching I'm not comfortable with.

Note that the solution for this is Rails version specific. The fix for Rails 5 (PPD, landing) will not work for Rails 6.

If we wanted to commit to this, we'd need to agree the details of the log messages. For example, should each one have a timestamp? Is `message` the right field? etc

**Comment by ijdickinson** [comment]
I documented my solution in this branch: https://github.com/epimorphics/ppd-explorer/tree/spike/puma-startup-shutdown-json

**Comment by ijdickinson** [comment]
Migrated to the central issues list, as https://github.com/epimorphics/hmlr-linked-data/issues/78
