### ISSUE TITLE
Trailing server.pid 

### ISSUE THREAD

**Issue by mika018** [epimorphics/ppd-explorer#149]
Sometimes rails leaves a trailing `/usr/src/app/tmp/pids/server.pid` file in the container causing it not to be able to restart. 
We fixed the latest incident reported here https://github.com/epimorphics/hmlr-ansible-deployment/issues/72 by removing the file manually but it would be nice if we can know exactly how it is left behind. 

A potential solution is to just add 
```
rm -f /usr/src/app/tmp/pids/server.pid
``` 
at the start of the `entrypoint.sh` script but not sure if that is the right solution. It is treating the consequence rather than the cause.

**Comment by ijdickinson** [comment]
A line to remove a residual `.pid` file has been added to the `entrypoint.sh` file
