### ISSUE TITLE
printing option on the PPD search tool no longer visible

### ISSUE THREAD

**Issue by alexrcoley** [epimorphics/ppd-explorer#191]
Susan (HMLR) reported:

>Please can you advise re the printing option on the PPD search tool – the print button is no longer available.
 https://landregistry.data.gov.uk/app/ppd/search

Note that it is still referenced in the help info:
![hmlr-print-ref](https://github.com/epimorphics/ppd-explorer/assets/1565598/f2aadc83-0264-4126-b292-bc2269c364d4)

**Comment by jonrandahl** [comment]
Closing as this is resolved and waiting for release with the new infrastructure:
![CleanShot 2023-10-09 at 12 20 46](https://github.com/epimorphics/ppd-explorer/assets/39102/c2d4ced7-4dd8-46df-a997-ce82d5a4f724)
