### ISSUE TITLE
Add page titles

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/ppd-explorer#220]
[2.4.2: Page Titled](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=154688571#gid=154688571&range=A12:I12)

**Comment by DanielCouzens** [comment]
There is a PR for common styles to update the title tag please see here https://github.com/epimorphics/lr_common_styles/pull/61

**Comment by DanielCouzens** [comment]
This is in review. PR https://github.com/epimorphics/ppd-explorer/pull/229

**Comment by DanielCouzens** [comment]
PR https://github.com/epimorphics/ppd-explorer/pull/229 is merged into dev

**Comment by tomguilbert** [comment]
@DanielCouzens this looks good but I think the Download Data page needs a title too.

**Comment by DanielCouzens** [comment]
@tomguilbert as far as I can see there is a separate title for the download page. Could you share a screenshot so I can pinpoint the issue?

**Comment by tomguilbert** [comment]
@DanielCouzens sure - when I go to the Download Data page the title of the tab in my browser doesn't change in the same way as it (now) does for the other pages in the service

<img width="529" alt="image" src="https://github.com/user-attachments/assets/749e3bc8-048c-4d17-b930-2ba1a5dad93f">

**Comment by DanielCouzens** [comment]
I have creates a PR to fix this https://github.com/epimorphics/ppd-explorer/pull/231

**Comment by tomguilbert** [comment]
Looks good thanks
