### ISSUE TITLE
Target size Icon is too small

### ISSUE THREAD

**Issue by DanielCouzens** [epimorphics/ppd-explorer#225]
The size of the target for pointer inputs is at least 24 by 24 CSS pixels

[2.5.8: Target Size (Minimum)](https://docs.google.com/spreadsheets/d/1YS3N5ps9pJGFOxBDi9C2DwA37WQPIVax/edit?gid=154688571#gid=154688571&range=A14)

**Comment by DanielCouzens** [comment]
Increases the size of the following targets to a min of 24px:

- ### Remove search term 

![Screenshot from 2024-08-09 10-45-48](https://github.com/user-attachments/assets/24d83590-2318-43b4-ae9b-0dc65b8d02ee)

- ### External link 

![Screenshot from 2024-08-09 11-09-00](https://github.com/user-attachments/assets/132b520b-24a7-40a7-a811-e3e0de1dde1e)

- ### Search zoom

![Screenshot from 2024-08-09 11-54-53](https://github.com/user-attachments/assets/029411df-7b0f-4383-8e95-37e22ac5d41a)

**Comment by DanielCouzens** [comment]
In review see PR https://github.com/epimorphics/ppd-explorer/pull/227

**Comment by DanielCouzens** [comment]
@tomguilbert this is ready to check on the dev instance https://hmlr-dev-pres.epimorphics.net/app/ppd/

NOTE: the icon is still small but the target area has increased.

**Comment by tomguilbert** [comment]
Looks good thanks Dan
