### ISSUE TITLE
Search results not displaying

### ISSUE THREAD

**Issue by tomguilbert** [epimorphics/ppd-explorer#232]
I'm getting this error page on the dev ppd app when I run any query (tried multiple queries, including v narrow - initial failure was for 'Rose Cottage' which I use as a default)

![Image](https://github.com/user-attachments/assets/829e0d6d-fd5e-4d20-b62c-9b130436200e)

**Comment by DanielCouzens** [comment]
This is in review https://github.com/epimorphics/ppd-explorer/pull/234

**Comment by DanielCouzens** [comment]
This has been merged

**Comment by DanielCouzens** [comment]
@tomguilbert this is ready to check

**Comment by tomguilbert** [comment]
Looks good thanks @DanielCouzens
