### ISSUE TITLE
Results page mag-glass filters don't toggle (low/medium)

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/ppd-explorer#35]
On the results page the mag-glass+ filters that show on the address fields don't toggle. I'd have expected the (mag-glass)+ to be replaced by a (mag-glass)-  in the same position so that a second click in the 'same' position would toggle the filter back off. It was a bit of a surprise to have to find the filter at the top of the page and toggle it off there.

**Comment by ijdickinson** [comment]
Migrated to https://github.com/epimorphics/hmlr-linked-data/issues/35
