### ISSUE TITLE
LR061 (Very low priority) Query button on SPARQL form blanks when clicked

### ISSUE THREAD

**Issue by SimonCannon** [epimorphics/ppd-explorer#61]
Very minor issue, raised just as an issue to consider for next major release

Run query button on SPARQL form is green and has text on it, but when clicked changes to white with no visible text (query runs fine)

Button stays same until you click somewhere else on the screen, when it reverts to original state

**Comment by ijdickinson** [comment]
@MalcolmShazell Do you know if this is still an issue, or can we close?

**Comment by MalcolmShazell** [comment]
working fine - just checked it
