### ISSUE TITLE
LR063 Metropolitan area search problem

### ISSUE THREAD

**Issue by ChrisJones123** [epimorphics/ppd-explorer#63]
Problem reported with incomplete results returned from the report builder for Greater London for a January 2014. The PDF published by LR on the 20th WD of April stated that there were in excess of 700 transactions for properties over £1 million in Greater London, a customer using the report builder to get those transactions returned a far lower result.
Investigation showed that reports on individual London Boroughs for the same period returned the correct result that could be combined to match the PDF but that any report for the ‘county’ of Greater London was incorrect. Further investigation on other metropolitan areas revealed similar results, that the sum of reports on individual areas that comprise the metropolitan area was greater than a report at the ‘county’ level. Potentially this is more of an issue for other areas as volumes are lower and the difference between the correct result and the result returned is less so.

In addition to London / Greater London areas affected are 

Greater Manchester
              Bolton, Bury, Manchester, Oldham, Rochdale, Salford, Stockport, Tameside, Trafford, Wigan.

Merseyside
            Knowsley, Liverpool, Sefton, St Helens, Wirral.

South Yorkshire
    Barnsley, Doncaster, Rotherham, Sheffield.

West Yorkshire
    Bradford, Calderdale, Kirklees, Leeds, Wakefield.

West Midlands
    Birmingham, Coventry, Dudley, Sandwell, Solihull, Walsall, Wolverhampton.

Tyne and Wear
    Gateshead, Newcastle upon Tyne, North Tyneside, South Tyneside, Sunderland.

Example results 
Sales for 500,000 or more in Manchester since 01 Jan 2014
County                      Transactions    Properties
Manchester                    11                       11
Greater Manchester            11                       11

Same search for the areas that comprise Manchester returns

District    Transactions    Properties
Bolton  3                   3
Bury            4                  4
Manchester  9          9
Oldham          1          1
Rochdale            2          2
Salford         0          0
Stockport           14         14
Tameside            1          1
Trafford            33         33
Wigan          1           1

Total       68       68

**Comment by ijdickinson** [comment]
@MalcolmShazell Do you know if this issue is still in need of investigating?

**Comment by MalcolmShazell** [comment]
I will investigate further to see if this is an issue - added to my backlog

**Comment by ijdickinson** [comment]
Assuming fixed or obsolete
