### ISSUE TITLE
LR064 SPARQL endpoint URL invalid on query screen. Low priority.

### ISSUE THREAD

**Issue by ChrisJones123** [epimorphics/ppd-explorer#65]
Looking at the SPARQL query page available here http://landregistry.data.gov.uk/app/hpi/qonsole. There's a link for a Land Registry SPARQL endpoint with this URL http://landregistry.data.gov.uk/landregistry/query displayed in the middle of the screen at the bottom which returns a 404 when pasted into a browser. 

Raised with Ian, this pasted from that e-mail

It's valid to HTTP POST to, it only returns a 404 when you HTTP GET (which is what happens when you paste the URL into a browser).

What should happen is that the redirect table in the web server config should redirect a GET on that URL back to the qonsole page.

**Comment by ijdickinson** [comment]
@MalcolmShazell I think this is obsolete now, and we can close. Do you agree?

**Comment by MalcolmShazell** [comment]
agree obsolete
