### ISSUE TITLE
Not finding transactions when street name contains a single quote character

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#72]
Search for postcode NW1 9RL and a number of properties in St Augustine's Road are returned.

Search for street matching "Augustine's" and no properties are returned.

Additional Info:

The query being issued is looking for streets matching ( Augustine AND s )

Do a text query for "Augustine's" 

SELECT *
WHERE
{
  
  ?addr text:query (lrcommon:street "Augustine's") .
  ?addr lrcommon:street ?street.
  
  OPTIONAL {?addr lrcommon:county ?county}
  OPTIONAL {?addr lrcommon:paon ?paon}
  OPTIONAL {?addr lrcommon:saon ?saon}
  OPTIONAL {?addr lrcommon:street ?street}
  OPTIONAL {?addr lrcommon:town ?town}
  OPTIONAL {?addr lrcommon:postcode ?postcode }

}
LIMIT 1

And a result is returned.

Do a similar query matching 'Augustine' and postcode NW1 9RL:

SELECT *
WHERE
{
  
  ?addr text:query (lrcommon:street "Augustine") .
  ?addr lrcommon:postcode "NW1 9RL"^^xsd:string .
  ?addr lrcommon:street ?street.
  
  OPTIONAL {?addr lrcommon:county ?county}
  OPTIONAL {?addr lrcommon:paon ?paon}
  OPTIONAL {?addr lrcommon:saon ?saon}
  OPTIONAL {?addr lrcommon:street ?street}
  OPTIONAL {?addr lrcommon:town ?town}
  OPTIONAL {?addr lrcommon:postcode ?postcode }

}
LIMIT 1

No results are returned, suggesting the term that is indexed is "Augustine's" not "Augustine"

**Comment by ijdickinson** [comment]
Generating the search term `Augustines` instead of `Augustine AND s` should now work. That won't fully address the issue, however, as the text indexer should take care to similarly sanitise punctuation characters in indexed terms. That's not something I have time to work on, but either you or Chris could do so.

**Comment by ijdickinson** [comment]
Since this is duplicated in Mal's report in #74 I'm going to close this one and comment in the other one.
