### ISSUE TITLE
failed searches with badly formatted dates have 200 response

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#73]
If a badly formatted date in entered into the search form, a 500 error is logged and the user gets the generic - "...large queries exceeding the time limit, or the result set being too large to transmit." error page.

**Comment by ijdickinson** [comment]
Details? As far as I can tell, a malformed date actually returns an 200 OK. Which it shouldn't (400 would be better), but nowhere can I see an error 500.

The generic error page is what the client wants.

**Comment by bwm-epimorphics** [comment]
This is more complicated than I thought.  I'll dig deeper and get back to it.

**Comment by bwm-epimorphics** [comment]
No its not complicated at all.  It is returning 200's as you say and that should be 4xx.

I'll update the title of this issue.

**Comment by ijdickinson** [comment]
Fix deployed to dev server.

**Comment by ijdickinson** [comment]
@MalcolmShazell This issue might need @bwmcbride to confirm the fix.

**Comment by MalcolmShazell** [comment]
agreed - @bwmcbride to confirm and close

**Comment by ijdickinson** [comment]
Assuming fixed
