### ISSUE TITLE
Towns with an apostrophe in the name not returning any results

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ppd-explorer#74]
*@MalcolmShazell reported this issue originally, but it's a problem with PPD not HPI, so I moved it to the PPD repo*.

I have tried with **Bishop's Stortford** and **king's lynn** got the same problem. I’m sure it is the `'` causing the problem - most probably its invalidating the SPARQL query. I tried running the following SPARQL with a town of DEAL which returned results and bishop's stortford which didn't. What is confusing me is both bits of SPARQL appear to parse correctly.

    prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    prefix owl: <http://www.w3.org/2002/07/owl#>
    prefix xsd: <http://www.w3.org/2001/XMLSchema#>
    prefix sr: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
    prefix lrhpi: <http://landregistry.data.gov.uk/def/hpi/>
    prefix lrppi: <http://landregistry.data.gov.uk/def/ppi/>
    prefix skos: <http://www.w3.org/2004/02/skos/core#>
    prefix lrcommon: <http://landregistry.data.gov.uk/def/common/>

    SELECT ?paon ?saon ?street ?town ?county ?postcode ?amount ?date
    WHERE
    {
      ?transx lrppi:pricePaid ?amount ;
              lrppi:transactionDate ?date ;
              lrppi:propertyAddress ?addr.
      
      ?addr lrcommon:town "Bishop's Stortford"^^xsd:string.
      ?addr lrcommon:town ?town.
      
      OPTIONAL {?addr lrcommon:county ?county}
      OPTIONAL {?addr lrcommon:paon ?paon}
      OPTIONAL {?addr lrcommon:saon ?saon}
      OPTIONAL {?addr lrcommon:street ?street}
      OPTIONAL {?addr lrcommon:postcode ?postcode}

    }
    ORDER BY ?amount

**Comment by ijdickinson** [comment]
When we were developing the PPD application, there was a concern that users should not accidentally or deliberately insert SPARQL or Lucene text query syntax into the query (i.e. something similar to an SQL injection attack). To guard against this, we agreed that all syntax characters, including single and double quotes, should be removed from the user's input in a normalisation step, before the query is submitted to the back-end query engine.

So the basic issue here is that the user inputs a search for **King's Lynn**, but the query submitted is for **Kings Lynn**. However, it seems that, at the moment, the text index is indexing the name *including* the apostrophe characters, so the index entry **KING'S LYNN** does not match the query term.

If that's correct, the question is what to do about it. We could choose to stop normalising the input, or at least to not remove single apostrophes. Or we could correct the text indexer so that it is indexing normalised names not un-normalised terms. The second option seems to me to be the more correct response, but would require more work.

**Comment by ijdickinson** [comment]
I've updated the tests and code to allow strings that contain a single apostrophe to go into the query unchanged. So search for `king's lynn` will work, but `king's lynn'` will get filtered. I think this will allow the majority of cases where users legitimately want to search for a string with an apostrophe in it, while still allowing us to filter out attempts to smuggle Lucene search syntax or other nefarities into the query.

**Comment by ijdickinson** [comment]
Fixed code now on `lr-pres-dev-c`

**Comment by MalcolmShazell** [comment]
I can confirm king's lynn and bishop's stalford work now. 
A couple of edge cases appear odd - not sure if we should consider fixing them 
king's lynn''' - doesn't return any results as expected however when going back to re-enter new data you need to fully refresh the page as king's lynn doesn't work - I think the query page may be hanging onto some of the ' when you just go back to make a new selection. - not too concerned as you probably have to be doing something you shouldn't to try that input
's doesn't return any results - essentially I was trying to find other addresses with apostrophes in - not sure if your code is designed to handle such a search string

**Comment by ijdickinson** [comment]
@MalcolmShazell I'm not sure I fully follow the first example, can you give more details please? On the second example, I wouldn't expect that to work from the UI. But you could do it from SPARQL!

**Comment by MalcolmShazell** [comment]
on the second issue - thats fine - I know someone will try it and it not being valid input for the UI is an acceptable answer - I will construct some SPARQL we can pass over to users in that circumstance.

The first issue
Humm - I could re-create this on friday but not today - have you put any other fixes on dev-c since I raised the defect?

**Comment by ijdickinson** [comment]
> have you put any other fixes on dev-c since I raised the defect?

No, I haven't done any updates recently.

**Comment by ijdickinson** [comment]
> on the second issue - that's fine

Great, thanks

**Comment by MalcolmShazell** [comment]
OK as I can't re-create the issue anymore i'll put it down to trying to work on a friday and close this - I will take a task to create the SPARQL to search for 's towns
