### ISSUE TITLE
Dev PPD report builder - creation of Sparql query from search parameters not working

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ppd-explorer#75]
When selecting the SPARQL query from the download options, the correct page is loaded but the SPARQL query is blank

**Comment by ijdickinson** [comment]
Sorry, I'm failing to reproduce this. What I did:

* start from a blank PPD search form
* search for `plymouth` and `show results`
* click the `download data` button
* click the `view SPARQL

**Comment by MalcolmShazell** [comment]
My apologies I was being a bit of a tool, I had java script turned off (something to note for gov guidelines on working with java script)

However when I click on the view sparql on the dev server It does not create the sparql for the search just performed like it does in live instead it presents the HPI search for plymouth SPARQL tried on both firefox and IE.

From IE in live search for 7 tenby road
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sr: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
prefix lrhpi: <http://landregistry.data.gov.uk/def/hpi/>
prefix lrppi: <http://landregistry.data.gov.uk/def/ppi/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix lrcommon: <http://landregistry.data.gov.uk/def/common/>

PREFIX  text: <http://jena.apache.org/text#>
PREFIX  ppd:  <http://landregistry.data.gov.uk/def/ppi/>
PREFIX  lrcommon: <http://landregistry.data.gov.uk/def/common/>

SELECT  ?item ?ppd_propertyAddress ?ppd_hasTransaction ?ppd_pricePaid ?ppd_publishDate ?ppd_transactionDate ?ppd_transactionId ?ppd_estateType ?ppd_newBuild ?ppd_propertyAddressCounty ?ppd_propertyAddressDistrict ?ppd_propertyAddressLocality ?ppd_propertyAddressPaon ?ppd_propertyAddressPostcode ?ppd_propertyAddressSaon ?ppd_propertyAddressStreet ?ppd_propertyAddressTown ?ppd_propertyType ?ppd_recordStatus
WHERE
  { ?ppd_propertyAddress text:query _:b0 .
    _:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "paon: ( 7 )  AND street: ( tenby AND road )" .
    _:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1 .
    _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> 3000000 .
    _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
    ?item ppd:propertyAddress ?ppd_propertyAddress .
    ?item ppd:hasTransaction ?ppd_hasTransaction .
    ?item ppd:pricePaid ?ppd_pricePaid .
    ?item ppd:publishDate ?ppd_publishDate .
    ?item ppd:transactionDate ?ppd_transactionDate .
    ?item ppd:transactionId ?ppd_transactionId
    OPTIONAL
      { ?item ppd:estateType ?ppd_estateType }
    OPTIONAL
      { ?item ppd:newBuild ?ppd_newBuild }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:county ?ppd_propertyAddressCounty }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:district ?ppd_propertyAddressDistrict }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:locality ?ppd_propertyAddressLocality }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:paon ?ppd_propertyAddressPaon }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:postcode ?ppd_propertyAddressPostcode }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:saon ?ppd_propertyAddressSaon }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:street ?ppd_propertyAddressStreet }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:town ?ppd_propertyAddressTown }
    OPTIONAL
      { ?item ppd:propertyType ?ppd_propertyType }
    OPTIONAL
      { ?item ppd:recordStatus ?ppd_recordStatus }
  }
LIMIT   100

from the same search on dev
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sr: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
prefix lrhpi: <http://landregistry.data.gov.uk/def/hpi/>
prefix lrppi: <http://landregistry.data.gov.uk/def/ppi/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix lrcommon: <http://landregistry.data.gov.uk/def/common/>

# Returns the house price indices for a particular local authority (Plymouth)
SELECT DISTINCT
  ?regionName ?yearmonth ?indexr ?region ?avgPriceAll ?avgDetached
  ?avgSemi ?avgFlats ?avgTerraced ?annual ?volume
WHERE
{
  values ?plymouth {<http://landregistry.data.gov.uk/data/hpi/region/city-of-plymouth/month/2013-01>}

  ?plymouth
    lrhpi:refRegion ?regionURI ;
    lrhpi:indicesSASM ?indexr ;
    lrhpi:refPeriod ?yearmonth ;
    lrhpi:averagePricesSASM ?avgPriceAll ;
    lrhpi:monthlyChange ?monthly ;
    lrhpi:averagePricesDetachedSASM ?avgDetached ;
    lrhpi:averagePricesSemiDetachedSASM ?avgSemi ;
    lrhpi:averagePricesFlatMaisonetteSASM ?avgFlats ;
    lrhpi:averagePricesTerracedSASM ?avgTerraced ;
    lrhpi:annualChange ?annual .

  OPTIONAL { ?plymouth lrhpi:salesVolume ?volume }

  ?regionURI rdfs:label ?regionName .
  FILTER (langMatches( lang(?regionName), "EN") )
}

**Comment by ijdickinson** [comment]
Fix deployed to dev server

**Comment by MalcolmShazell** [comment]
fix confirmed - closed
