### ISSUE TITLE
turtle download is not valid turtle syntax

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#79]
turtle downloads have syntax errors, e.g.  

> http://landregistry.data.gov.uk/data/ppi/address/ae43291073c9c89fc7035d4eadc614a1d71d9b16
>     a common:BS7666Address ;
>     common:county default CITY OF KINGSTON UPON HULL ;
>     common:district default CITY OF KINGSTON UPON HULL ;
>     common:town default HULL ;
>     common:locality default HULL ;
>     common:street default KINGS BENCH STREET ;
>     common:paon default 64 ;
>     common:postcode default HU3 2TX ;
>     .

Steps to reproduce:
- visit http://landregistry.data.gov.uk/app/ppd
- enter '64' in the building name or number field
- enter 'HU3 2TX' in the postcode field
- press "show results" button
- press "download data" button
- press "get selected results as turtle" button

**Comment by ijdickinson** [comment]
Hmm. There has been a regression here. The `default` flag was something I put in to flag up predicates that were hitting the default renderer rather than the type-based renderer. It used to not be be the case that any `default` lines showed up in the Turtle output. I'll dig into it (at some point), but is it possible that the data has changed in any way?

**Comment by bwmcbride** [comment]
I'm not aware of any data model changes.

The data itself changes regularly, of course.

Brian


On 07/03/16 11:00, Ian Dickinson wrote:
>
> Hmm. There has been a regression here. The |default| flag was 
> something I put in to flag up predicates that were hitting the default 
> renderer rather than the type-based renderer. It used to not be be the 
> case that any |default| lines showed up in the Turtle output. I'll dig 
> into it (at some point), but is it possible that the data has changed 
> in any way?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/epimorphics/ppd-explorer/issues/79#issuecomment-193205165>.
>

-- 
Epimorphics Ltd, http://www.epimorphics.com
Registered address: Court Lodge, 105 High Street, Portishead, Bristol BS20 6PT
Epimorphics Ltd. is a limited company registered in England (number 7016688)

**Comment by ijdickinson** [comment]
Assuming fixed
