### ISSUE TITLE
Reduce memory footprint?

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#80]
When downloading a lot of data, a single ppd-explorer process can consume 15G of ram out of the 30 available on a presentation server.  This can be seen by observing the system in top and then:
- visit /app/ppd
- type london into the the town field
- click show results
- click download data
- click get all results as csv with headers

In the past we have tried to control memory usage by limiting the number of processes, but that doesn't work if a single process can use 15GB of ram.

Observing the application in top, there appear to be two phases.  In the first, cpu load is relatively low, < 10% and the resident memory footprint grows to about 3G.  During this phase tomcat is busy.  This probaly corresponds to the app aquiring the data.  In the second phase the CPU load is much higher and the resident memory footprint grows to 15GB.

Are there opportunities to reduce the memory usage?

**Comment by ijdickinson** [comment]
Assuming fixed
