### ISSUE TITLE
Non-styled calendars

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ppd-explorer#84]
@bwmcbride mentioned in passing on Slack:

> The pop up calendars have lost their background and don't look right in chrome and firefox

**Comment by MalcolmShazell** [comment]
Background fixed but doesn't look to me like searching by date works - searched plymouth and devon for all of may and got no results

**Comment by ijdickinson** [comment]
@MalcolmShazell I don't think the triple store on the staging data server has up-to-date data. Searching for May 2015 Plymouth does work.

**Comment by MalcolmShazell** [comment]
OK I was being a turkey :) happy to close this and the two fixes to be deployed when convenient for you
