### ISSUE TITLE
New build filter not displaying correctly

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ppd-explorer#86]
When you select new build or not new build and run the search, the list of search terms on the result page contains "new build? is" for both new build and not new build selections. 

See attached 
![new build error](https://cloud.githubusercontent.com/assets/6670586/18782958/f079b492-8180-11e6-98b8-18a5ab10f5e2.jpg)

**Comment by ijdickinson** [comment]
@MalcolmShazell There's a version to test up now on `lr-pres-dev-c`. It's worth giving it a bit of a going over, because I've also update the application to Rails 5 as well. Which, in theory, hasn't broken anything.

**Comment by ijdickinson** [comment]
@MalcolmShazell I think we can close this now?

**Comment by MalcolmShazell** [comment]
yes - I totally forgot to close this off
