### ISSUE TITLE
Slow or failure to select all transactions for a month when system under load

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#89]
To reproduce:  [[

Visit 

http://lr-pres-staging-b.epimorphics.net/app/ppd

Enter the start and end dates for one calendar month, e.g. 1/Nov/2016 and 30/Nov/2016

Press show results.

This either takes a while or times out, depending on how busy the machine is and whether the caches are warm with the right data.

]]

This request results in two queries going to the data server, the first of which is of the form:

[[

PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#> 
PREFIX  ppd:  <http://landregistry.data.gov.uk/def/ppi/> 
PREFIX  lrcommon: <http://landregistry.data.gov.uk/def/common/>  
SELECT  ?item 
# ...
    WHERE   { 

  ?item ppd:transactionDate ?ppd_transactionDate .    
# ...
   FILTER ( ?ppd_transactionDate >= "2016-11-01"^^xsd:date )     
   FILTER ( ?ppd_transactionDate <= "2016-11-30"^^xsd:date )  
} LIMIT   100 
]]

The actual query has more detail, but this simple form alone about 55 seconds to execute on an otherwise idle machine with caches warmed.

The reason this query is so slow is that date range filters on Fuseki are slow.  They seem to require examining the dates of all the transactions.

An alternative form of the query which unfolds the date range and  looks for the specific dates in the month runs in about 5ms, viz:

[[
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#> 
PREFIX  ppd:  <http://landregistry.data.gov.uk/def/ppi/> 
PREFIX  lrcommon: <http://landregistry.data.gov.uk/def/common/>  
SELECT  ?item
# ...

   WHERE   { 
    VALUES ?ppd_transactionDate {
      "2016-11-01"^^xsd:date
      "2016-11-02"^^xsd:date
      "2016-11-03"^^xsd:date
      "2016-11-04"^^xsd:date
      "2016-11-05"^^xsd:date
      "2016-11-06"^^xsd:date
      "2016-11-07"^^xsd:date
      "2016-11-08"^^xsd:date
      "2016-11-09"^^xsd:date
      "2016-11-10"^^xsd:date
      "2016-11-11"^^xsd:date
      "2016-11-12"^^xsd:date
      "2016-11-13"^^xsd:date
      "2016-11-14"^^xsd:date
      "2016-11-15"^^xsd:date
      "2016-11-16"^^xsd:date
      "2016-11-17"^^xsd:date
      "2016-11-18"^^xsd:date
      "2016-11-19"^^xsd:date
      "2016-11-20"^^xsd:date
      "2016-11-21"^^xsd:date
      "2016-11-22"^^xsd:date
      "2016-11-23"^^xsd:date
      "2016-11-24"^^xsd:date
      "2016-11-25"^^xsd:date
      "2016-11-26"^^xsd:date
      "2016-11-27"^^xsd:date
      "2016-11-28"^^xsd:date
      "2016-11-29"^^xsd:date
      "2016-11-30"^^xsd:date
   }
   ?item ppd:transactionDate ?ppd_transactionDate .
} LIMIT 100
]]

Discussions with Chris suggests that a query of this form could be generated by the app using the 'oneof' construct in the dsapi.

Possibly, unfolding the dates will significantly speed up requests of this type.

Caveats:

- only tested with one months worth of date range.  Need to decide how wide a date range should be unfolded.
- not tested when there are other filters in place which would narrow the search
- not tested when pulling back other values

**Comment by ijdickinson** [comment]
Assuming fixed or obsolete
