### ISSUE TITLE
View Sparql for a report does not create the sparql properly 

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ppd-explorer#93]
I used PL4 in the postcode to create a PPD results set - whenn i used download, view SPARQL the SPARQL produced generated a parse error:

REFIX  text: <http://jena.apache.org/text#>
PREFIX  ppd:  <http://landregistry.data.gov.uk/def/ppi/>
PREFIX  lrcommon: <http://landregistry.data.gov.uk/def/common/>

SELECT  ?item ?ppd_propertyAddress ?ppd_hasTransaction ?ppd_pricePaid ?ppd_transactionCategory ?ppd_transactionDate ?ppd_transactionId ?ppd_estateType ?ppd_newBuild ?ppd_propertyAddressCounty ?ppd_propertyAddressDistrict ?ppd_propertyAddressLocality ?ppd_propertyAddressPaon ?ppd_propertyAddressPostcode ?ppd_propertyAddressSaon ?ppd_propertyAddressStreet ?ppd_propertyAddressTown ?ppd_propertyType ?ppd_recordStatus
WHERE
  { { SELECT  ?ppd_propertyAddress ?item ?ppd_pricePaid ?ppd_transactionCategory ?ppd_transactionDate ?ppd_transactionId ?ppd_hasTransaction
      WHERE
        { ?ppd_propertyAddress
                    text:query            _:b0 .
          _:b0      <http://www.w3.org/1999/02/22-rdf-syntax-ns#first>  lrcommon:postcode

**Comment by ijdickinson** [comment]
Assuming fixed
