### ISSUE TITLE
Download with headers option headers missing

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/ppd-explorer#94]
Originally the query cane from a user, they provided a link where if you selected download with headers no headers appeared
http://landregistry.data.gov.uk/app/ppd/ppd_data?et%5B%5D=lrcommon%3Afreehold&et%5B%5D=lrcommon%3Aleasehold&limit=all&nb%5B%5D=true&nb%5B%5D=false&ptype%5B%5D=lrcommon%3Adetached&ptype%5B%5D=lrcommon%3Asemi-detached&ptype%5B%5D=lrcommon%3Aterraced&ptype%5B%5D=lrcommon%3Aflat-maisonette&ptype%5B%5D=lrcommon%3AotherPropertyType&tc%5B%5D=ppd%3AstandardPricePaidTransaction&tc%5B%5D=ppd%3AadditionalPricePaidTransaction&town=Bristol

That is a big file and slow to use, after further investigation i've identified 2 searches
town:Plymouth street:Neath road all entries - this generates a csv with headers - 174 records
town:plymouth street: saltash road all entries - this generates a csv with no headers - 231 records 

not sure what can be causing this - maybe its a number of records thing?
BTW i've searched the csv for county which is one of the headers and its not there so its not doing something weird like sorting the header row into the file

**Comment by ijdickinson** [comment]
I can't repro the smaller examples in Plymouth (I get headers for both examples if I click the `with headers` link), but I can observe the issue with the large request from the user. Investigating.

**Comment by MalcolmShazell** [comment]
That’s weird – it defo didn’t work for me on the second Plymouth example – I was using firefox but I will try again tonight

**Comment by ijdickinson** [comment]
@MalcolmShazell I can see why the headers are missing on a large CSV file - just a bug in my code. Working on a fix now.

**Comment by ijdickinson** [comment]
@MalcolmShazell There's a fixed version now deployed on the dev server, if you'd like to test when you have a free moment please.

**Comment by ijdickinson** [comment]
Assuming fixed
