### ISSUE TITLE
Unhelpful response when browser has cookies disabled

### ISSUE THREAD

**Issue by bwmcbride** [epimorphics/ppd-explorer#96]
Visit:

- Disable setting cookies in the browser (chrome in my case)
- 
- go to http://landregistry.data.gov.uk/app/ppd
- 
- enter plymouth in the town or city field
- 
- press show results

Get an unhelpful response ( the update you requested is not permitted (or something like that ))

Two things:

- should the user be required to enable setting of cookies to access this service?
- if so, the error response should tell the user why there request is being rejected

**Comment by ijdickinson** [comment]
I don't think this is a valid issue. The only way I could reproduce this behaviour in Firefox is to select the setting "Reject all cookies (warning: this will cause some sites to break)". So any user who **does** choose this setting has been pre-warned.

The only cookie used is the session cookie, which is used to store the authenticity token that prevents cross-site scripting attacks. I don't see an obvious way to explain that to a user that wouldn't be confusing. 

In five years of operation, we have had zero reports about this from actual users.

@MalcolmShazell Do you have an opinion?

**Comment by bwmcbride** [comment]
An error message that said something like

Error.  Unable to set an essential cookie that is required to keep your browser data secure.

would have given me a clue.  I don't think that is too complicated for actual users.  YMMV.

The error threw me for a bit when it happened, but I agree its not going to be a common occurrence - so not urgent.

**Comment by ijdickinson** [comment]
@bwmcbride @MalcolmShazell We still haven't had any user reports of this being a problem. I'm going to close unless you strongly feel otherwise?

**Comment by ijdickinson** [comment]
Closing
